{{ if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-mongodb-pvc
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
{{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}
{{ end }}