tasks:
  - name: Add daily cloud service summary
    id: daily_cloud_service_summary
    uses: "@modules/resource"
    spec:
      resource_type: statistics.Schedule
      data:
        domain_id: ${{ tasks.domain.output.domain_id }}
        topic: daily_cloud_service_summary
        schedule:
          hours:
            - 1
        options:
          aggregate:
            - query:
                resource_type: inventory.Server
                query:
                  aggregate:
                  - group:
                      keys:
                      - name: project_id
                        key: project_id
                      - name: cloud_service_type
                        key: cloud_service_type
                      - name: cloud_service_group
                        key: cloud_service_group
                      - name: provider
                        key: provider 
                      fields:
                      - name: value
                        operator: count
                  filter:
                  - key: ref_cloud_service_type.is_primary
                    operator: eq
                    value: true
                extend_data:
                  label: Compute
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - name: value
                          operator: count
                    filter:
                    - key: ref_cloud_service_type.is_primary
                      operator: eq
                      value: true
                    - key: ref_cloud_service_type.labels
                      operator: eq
                      value: Database
                extend_data:
                    label: Database
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - name: value
                          operator: count
                    filter:
                    - key: ref_cloud_service_type.is_primary
                      operator: eq
                      value: true
                    - key: ref_cloud_service_type.labels
                      operator: eq
                      value: Container 
                extend_data:
                    label: Container
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - name: value
                          operator: count
                    filter:
                    - key: ref_cloud_service_type.is_primary
                      operator: eq
                      value: true
                    - key: ref_cloud_service_type.labels
                      operator: eq
                      value: Networking 
                extend_data:
                    label: Networking 
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - name: value
                          operator: count
                    filter:
                    - key: ref_cloud_service_type.is_primary
                      operator: eq
                      value: true
                    - key: ref_cloud_service_type.labels
                      operator: eq
                      value: Security 
                extend_data:
                    label: Security 
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - name: value
                          operator: count
                    filter:
                    - key: ref_cloud_service_type.is_primary
                      operator: eq
                      value: true
                    - key: ref_cloud_service_type.labels
                      operator: eq
                      value: Analytics 
                extend_data:
                    label: Analytics 
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - name: value
                          operator: count
                    filter:
                    - key: ref_cloud_service_type.is_primary
                      operator: eq
                      value: true
                extend_data:
                    label: All  
            - concat:
                resource_type: inventory.CloudService
                query:
                    aggregate:
                    - group:
                        keys:
                        - name: project_id
                          key: project_id
                        - name: cloud_service_type
                          key: cloud_service_type
                        - name: cloud_service_group
                          key: cloud_service_group
                        - name: provider
                          key: provider 
                        fields:
                        - key: data.size
                          name: value
                          operator: sum
                    filter:
                    - key: ref_cloud_service_type.is_major
                      operator: eq
                      value: true
                    - key: ref_cloud_service_type.labels
                      operator: eq
                      value: Storage
                extend_data:
                    label: Storage
      mode: EXEC
      verb:
        exec: add


