# deploy always
apiVersion: v1
kind: ConfigMap
metadata:
  name: spacectl-environment-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  environment.yml: |
    environment: helm-root
  helm-root.yml: |
    endpoints:
      config: grpc://config:50051
      identity: grpc://identity:50051
      inventory: grpc://inventory:50051
      monitoring: grpc://monitoring:50051
      plugin: grpc://plugin:50051
      repository: grpc://repository:50051
      secret: grpc://secret:50051
      statistics: grpc://statistics:50051
